name: Deploy ACA

on:
  push:
  
permissions:
    id-token: write
    contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: 'Az CLI login'
      uses: azure/login@v1.5.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
    - name: Terraform init
      run: terraform init -upgrade
    - name: Terraform import
      run: terraform import
    - name: Terraform apply
      run: terraform apply --auto-approve