name: Deploy ACA

on:
  push:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
    - name: Terraform init
      run: terraform init
    - name: Terraform apply
      run: terraform apply